import type { Metadata } from "next";
import "./globals.css";
import { Zen_Dots } from "next/font/google";

const zendots = Zen_Dots({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Gainz Journal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${zendots.className} antialiased`}>{children}</body>
    </html>
  );
}
