import type { Metadata } from "next";
import "./globals.css";
import { CgHome, CgMenuLeft } from "react-icons/cg";

export const metadata: Metadata = {
  title: "Gainz Journal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <header>
          <nav className="flex justify-between items-center p-4 fixed w-full top-0 text-primary">
            <CgMenuLeft size={30} className="cursor-pointer" />
            <CgHome size={25} className="cursor-pointer" />
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
